import kind from '@enact/core/kind';
import Repeater from "@enact/ui/Repeater";
import Folder from "../Folder/Folder";
import Icon from '@enact/sandstone/Icon';

const folders = [
	"Startek",
	"Music",
	"Video",
	"Audio",
	"Records",
	"Logs",
	"Wav",
	"New",
	"Default",
	"12345",
	"Android",
	"Data",
	"Obb",
	"Week1",
	"August",
	"Week2",
	"[FHD,UHD]Default",
	"Week3",
	"March",
	"[Subtitle]",
	"ScreenShots",
  ];



const FolderRepeater = kind({
	name: 'FolderRepeater',


	render: ({onNavigate,...rest}) => {	
		console.log(onNavigate)
		return (
			
			<Repeater childComponent={Folder} indexProp="index" itemProps={{onNavigate}}>
          {folders}
        </Repeater>
		);
	}
});

export default FolderRepeater;



//   const Iconss = kind({
// 	  name:"Iconss",
// 	  render: ({children, index,onNavigate,handleClick, ...rest}) => {
// 		return (
// 			<div {...rest}>
//                     {index}:<Icon>{children}</Icon>
// 			</div>
// 		);
// 	}
//   })

// const arr = [
// 	"plus",
// 	"minus",
// 	"arrowhookleft",
// 	"arrowhookright",
// 	"ellipsis",
// 	"check",
// 	"triangleup",
// 	"triangleright",
// 	"triangledown",
// 	"triangleleft",
// 	"arrowupdown",
// 	"arrowup",
// 	"arrowupwhite",
// 	"arrowuphollow",
// 	"backspace",
// 	"space",
// 	"trianglerightwhite",
// 	"triangleleftwhite",
// 	"trianglerighthollow",
// 	"trianglelefthollow",
// 	"heart",
// 	"hearthollow",
// 	"record",
// 	"circle",
// 	"stop",
// 	"square",
// 	"play",
// 	"pause",
// 	"forward",
// 	"backward",
// 	"pauseforward",
// 	"pausebackward",
// 	"pausejumpforward",
// 	"pausejumpbackward",
// 	"jumpforward",
// 	"jumpbackward",
// 	"skip",
// 	"list",
// 	"arrowlargedown",
// 	"arrowlargeup",
// 	"arrowlargeleft",
// 	"arrowlargeright",
// 	"arrowsmallup",
// 	"arrowsmalldown",
// 	"arrowsmallleft",
// 	"arrowsmallright",
// 	"closex",
// 	"search",
// 	"chup",
// 	"chdown",
// 	"exitfullscreen",
// 	"fullscreen",
// 	"trash",
// 	"star",
// 	"starhalf",
// 	"starhollow",
// 	"gear",
// 	"plug",
// 	"lock",
// 	"music",
// 	"view360",
// 	"info",
// 	"verticalellipsis",
// 	"arrowcurveright",
// 	"picture",
// 	"home",
// 	"liverecord",
// 	"liveplay",
// 	"trashlock",
// 	"movecursor",
// 	"repeatone",
// 	"repeatall",
// 	"repeatnone",
// 	"zoomin",
// 	"zoomout",
// 	"download",
// 	"shuffle",
// 	"shuffleon",
// 	"notification",
// 	"voice",
// 	"soundmute",
// 	"stargroup",
// 	"checker",
// 	"transponder",
// 	"selected",
// 	"bgm",
// 	"bgmoff",
// 	"playcircle",
// 	"pausecircle",
// 	"lockcircle",
// 	"unlockcircle",
// 	"powercircle",
// 	"wifi1",
// 	"wifi2",
// 	"wifi3",
// 	"wifi4",
// 	"wifilock1",
// 	"wifilock2",
// 	"wifilock3",
// 	"wifilock4",
// 	"dashboard1",
// 	"dashboard2",
// 	"dashboard3",
// 	"language",
// 	"rotate",
// 	"lyrics",
// 	"screenpower",
// 	"miniplayer",
// 	"nowplaying",
// 	"playspeed",
// 	"folder",
// 	"folderupper",
// 	"support",
// 	"soundout",
// 	"mobile",
// 	"keyboard",
// 	"mouse",
// 	"controller",
// 	"btspeaker",
// 	"headset",
// 	"dns",
// 	"speaker",
// 	"speakersurround",
// 	"speakercenter",
// 	"speakerbass",
// 	"router",
// 	"demosync",
// 	"browser",
// 	"sound",
// 	"wisa",
// 	"demooptions",
// 	"newfeature",
// 	"youtube",
// 	"ostsearch",
// 	"shopping",
// 	"bookmark",
// 	"eject",
// 	"power",
// 	"timer",
// 	"network",
// 	"edit",
// 	"aspectratio",
// 	"link",
// 	"light",
// 	"pointersize",
// 	"pointerspeed",
// 	"soundmode",
// 	"contrast",
// 	"picturemode",
// 	"basketball",
// 	"soccer",
// 	"baseball",
// 	"golf",
// 	"football",
// 	"hockey",
// 	"volleyball",
// 	"cricket",
// 	"heartadd",
// 	"heartlist",
// 	"refresh",
// 	"help",
// 	"share",
// 	"files",
// 	"quickstart",
// 	"scheduler",
// 	"recording",
// 	"guide",
// 	"channel",
// 	"oneminplay",
// 	"oneminrecord",
// 	"fifteenforward",
// 	"fifteenbackward",
// 	"liveplayoff",
// 	"liveplayon",
// 	"popupscale",
// 	"arrowrightskip",
// 	"closedcaption",
// 	"subtitle",
// 	"subtitlekr",
// 	"subtitlecn",
// 	"samples",
// 	"googledrive",
// 	"googlephotos",
// 	"dlna",
// 	"replay",
// 	"usb",
// 	"ftp",
// 	"profile",
// 	"profilecheck",
// 	"mediaserver",
// 	"spanner",
// 	"bluetooth",
// 	"moodmode",
// 	"changepassword",
//   ];
